import type { EmailTemplateDoc, EmailTemplateKey, TemplateLocale } from "@/lib/types/events";
import { paymentBankBlock, paymentDeadlineBlock } from "@/lib/events/payment-details";

export const EMAIL_TEMPLATE_KEYS: EmailTemplateKey[] = [
  "calendar_invite",
  "participation_confirmed",
  "reminder_7d",
  "reminder_36h",
  "reminder_90m",
  "satisfaction_survey",
  "light_signup",
  "referral_invite",
];

export const TEMPLATE_LOCALES: TemplateLocale[] = ["es", "fr", "en"];

/** Default language for email + WhatsApp sends when event has no language. */
export const DEFAULT_SEND_LOCALE: TemplateLocale = "es";

export const EMAIL_TEMPLATE_LABELS: Record<EmailTemplateKey, string> = {
  calendar_invite: "Invitation calendrier (ICS + YES/NO)",
  participation_confirmed: "Confirmation après paiement",
  reminder_7d: "Rappel J-7 (legacy email — préférer VALARM ICS)",
  reminder_36h: "Rappel H-36 (legacy email — préférer VALARM ICS)",
  reminder_90m: "Rappel H-1h30 (legacy email — préférer VALARM ICS)",
  satisfaction_survey: "Questionnaire satisfaction (+12h, cron 1×/jour)",
  light_signup: "Inscription express (/light) — compléter le profil",
  referral_invite:
    "Invitation ami (parrainage / satisfaction « Sí, invitar »)",
};

export const TEMPLATE_LOCALE_LABELS: Record<TemplateLocale, string> = {
  es: "Español",
  fr: "Français",
  en: "English",
};

type LocalePair = { subject: string; body: string };

const DEFAULTS: Record<EmailTemplateKey, Record<TemplateLocale, LocalePair>> = {
  calendar_invite: {
    es: {
      subject: "Invitación LA MESA — {{eventTitle}}",
      body: [
        "Estimado/a {{fullName}}:",
        "",
        "Te invitamos a la cena privada LA MESA: {{eventTitle}}.",
        "",
        "Fecha y hora: {{when}}",
        "Lugar: {{where}}",
        "",
        "Menú e incluidos:",
        "{{menuIncluded}}",
        "",
        "Monto a pagar:",
        "Precio: {{priceBeforeTax}}",
        "IVA (16 %): {{ivaAmount}}",
        "Total: {{totalWithIva}}",
        "",
        paymentDeadlineBlock("es"),
        "",
        paymentBankBlock("es"),
        "",
        "Confirma tu asistencia (selecciona YES o NO):",
        "YES: {{yesUrl}}",
        "NO: {{noUrl}}",
        "",
        "Página del evento: {{eventUrl}}",
        "",
        "Adjuntamos un archivo de calendario (.ics) a este correo.",
        "",
        "Quedamos a tus órdenes,",
        "LA MESA",
      ].join("\n"),
    },
    fr: {
      subject: "Invitation LA MESA — {{eventTitle}}",
      body: [
        "Bonjour {{fullName}},",
        "",
        "Tu es invité(e) au dîner privé LA MESA : {{eventTitle}}.",
        "",
        "Quand : {{when}}",
        "Où : {{where}}",
        "",
        "Menu & inclus :",
        "{{menuIncluded}}",
        "",
        "Montant à régler :",
        "Prix : {{priceBeforeTax}}",
        "IVA (16%) : {{ivaAmount}}",
        "Total : {{totalWithIva}}",
        "",
        paymentDeadlineBlock("fr"),
        "",
        paymentBankBlock("fr"),
        "",
        "Confirme ta présence (clique YES ou NO) :",
        "YES : {{yesUrl}}",
        "NO : {{noUrl}}",
        "",
        "Page de l’événement : {{eventUrl}}",
        "",
        "Un fichier calendrier (.ics) est joint à cet email.",
        "",
        "À bientôt,",
        "LA MESA",
      ].join("\n"),
    },
    en: {
      subject: "LA MESA invitation — {{eventTitle}}",
      body: [
        "Hi {{fullName}},",
        "",
        "You’re invited to a private LA MESA dinner: {{eventTitle}}.",
        "",
        "When: {{when}}",
        "Where: {{where}}",
        "",
        "Menu & included:",
        "{{menuIncluded}}",
        "",
        "Amount due:",
        "Price: {{priceBeforeTax}}",
        "IVA (16%): {{ivaAmount}}",
        "Total: {{totalWithIva}}",
        "",
        paymentDeadlineBlock("en"),
        "",
        paymentBankBlock("en"),
        "",
        "Confirm your attendance (tap YES or NO):",
        "YES: {{yesUrl}}",
        "NO: {{noUrl}}",
        "",
        "Event page: {{eventUrl}}",
        "",
        "A calendar file (.ics) is attached to this email.",
        "",
        "See you soon,",
        "LA MESA",
      ].join("\n"),
    },
  },
  participation_confirmed: {
    es: {
      subject: "Participación confirmada — {{eventTitle}}",
      body: [
        "Estimado/a {{fullName}}:",
        "",
        "Confirmamos tu participación en la cena « {{eventTitle}} ».",
        "",
        "Fecha y hora: {{when}}",
        "Lugar: {{where}}",
        "",
        "Detalles: {{eventUrl}}",
        "",
        "Quedamos a tus órdenes,",
        "LA MESA",
      ].join("\n"),
    },
    fr: {
      subject: "Participation confirmée — {{eventTitle}}",
      body: [
        "Bonjour {{fullName}},",
        "",
        "Ta participation au dîner {{eventTitle}} est confirmée.",
        "",
        "Quand : {{when}}",
        "Où : {{where}}",
        "",
        "Détails : {{eventUrl}}",
        "",
        "Au plaisir de te retrouver,",
        "LA MESA",
      ].join("\n"),
    },
    en: {
      subject: "Participation confirmed — {{eventTitle}}",
      body: [
        "Hi {{fullName}},",
        "",
        "Your spot at {{eventTitle}} is confirmed.",
        "",
        "When: {{when}}",
        "Where: {{where}}",
        "",
        "Details: {{eventUrl}}",
        "",
        "Looking forward to seeing you,",
        "LA MESA",
      ].join("\n"),
    },
  },
  reminder_7d: {
    es: {
      subject: "Recordatorio — {{eventTitle}} (falta 1 semana)",
      body: [
        "Estimado/a {{fullName}}:",
        "",
        "Te recordamos que la cena LA MESA « {{eventTitle}} » tendrá lugar en una semana.",
        "",
        "Fecha y hora: {{when}}",
        "Lugar: {{where}}",
        "",
        "{{eventUrl}}",
        "",
        "Quedamos a tus órdenes,",
        "LA MESA",
      ].join("\n"),
    },
    fr: {
      subject: "Rappel J-7 — {{eventTitle}}",
      body: [
        "Bonjour {{fullName}},",
        "",
        "Rappel : le dîner LA MESA « {{eventTitle}} » a lieu dans une semaine.",
        "",
        "Quand : {{when}}",
        "Où : {{where}}",
        "",
        "{{eventUrl}}",
        "",
        "LA MESA",
      ].join("\n"),
    },
    en: {
      subject: "Reminder 7 days — {{eventTitle}}",
      body: [
        "Hi {{fullName}},",
        "",
        "Reminder: the LA MESA dinner “{{eventTitle}}” is in one week.",
        "",
        "When: {{when}}",
        "Where: {{where}}",
        "",
        "{{eventUrl}}",
        "",
        "LA MESA",
      ].join("\n"),
    },
  },
  reminder_36h: {
    es: {
      subject: "Recordatorio — {{eventTitle}} (en 36 horas)",
      body: [
        "Estimado/a {{fullName}}:",
        "",
        "La cena « {{eventTitle}} » tendrá lugar en aproximadamente 36 horas.",
        "",
        "Fecha y hora: {{when}}",
        "Lugar: {{where}}",
        "",
        "{{eventUrl}}",
        "",
        "Quedamos a tus órdenes,",
        "LA MESA",
      ].join("\n"),
    },
    fr: {
      subject: "Rappel — {{eventTitle}} dans 36h",
      body: [
        "Bonjour {{fullName}},",
        "",
        "Le dîner « {{eventTitle}} » a lieu dans environ 36 heures.",
        "",
        "Quand : {{when}}",
        "Où : {{where}}",
        "",
        "{{eventUrl}}",
        "",
        "LA MESA",
      ].join("\n"),
    },
    en: {
      subject: "Reminder — {{eventTitle}} in 36h",
      body: [
        "Hi {{fullName}},",
        "",
        "The dinner “{{eventTitle}}” is in about 36 hours.",
        "",
        "When: {{when}}",
        "Where: {{where}}",
        "",
        "{{eventUrl}}",
        "",
        "LA MESA",
      ].join("\n"),
    },
  },
  reminder_90m: {
    es: {
      subject: "Último recordatorio — {{eventTitle}} (en 1 h 30)",
      body: [
        "Estimado/a {{fullName}}:",
        "",
        "Te esperamos en 1 hora y 30 minutos para « {{eventTitle}} ».",
        "",
        "Fecha y hora: {{when}}",
        "Lugar: {{where}}",
        "",
        "{{eventUrl}}",
        "",
        "Hasta pronto,",
        "LA MESA",
      ].join("\n"),
    },
    fr: {
      subject: "Dernier rappel — {{eventTitle}} dans 1h30",
      body: [
        "Bonjour {{fullName}},",
        "",
        "Rendez-vous dans 1h30 pour {{eventTitle}}.",
        "",
        "Quand : {{when}}",
        "Où : {{where}}",
        "",
        "{{eventUrl}}",
        "",
        "À tout de suite,",
        "LA MESA",
      ].join("\n"),
    },
    en: {
      subject: "Final reminder — {{eventTitle}} in 90 min",
      body: [
        "Hi {{fullName}},",
        "",
        "See you in 90 minutes for {{eventTitle}}.",
        "",
        "When: {{when}}",
        "Where: {{where}}",
        "",
        "{{eventUrl}}",
        "",
        "See you soon,",
        "LA MESA",
      ].join("\n"),
    },
  },
  satisfaction_survey: {
    es: {
      subject: "Gracias por {{eventTitle}} — tu opinión nos importa",
      body: [
        "Estimado/a {{fullName}}:",
        "",
        "Gracias por haber participado en la cena LA MESA « {{eventTitle}} ».",
        "",
        "Para ayudarnos a mejorar las próximas mesas, te pedimos un minuto para evaluar tu experiencia:",
        "{{surveyUrl}}",
        "",
        "Quedamos a tus órdenes,",
        "LA MESA",
      ].join("\n"),
    },
    fr: {
      subject: "Merci pour {{eventTitle}} — ton avis compte",
      body: [
        "Bonjour {{fullName}},",
        "",
        "Merci d’avoir participé au dîner LA MESA « {{eventTitle}} ».",
        "",
        "Pour nous aider à améliorer les prochaines tables, prends 1 minute pour noter ton expérience :",
        "{{surveyUrl}}",
        "",
        "À bientôt,",
        "LA MESA",
      ].join("\n"),
    },
    en: {
      subject: "Thanks for {{eventTitle}} — we’d love your feedback",
      body: [
        "Hi {{fullName}},",
        "",
        "Thanks for joining the LA MESA dinner “{{eventTitle}}”.",
        "",
        "Help us improve the next tables — take 1 minute to rate your experience:",
        "{{surveyUrl}}",
        "",
        "See you soon,",
        "LA MESA",
      ].join("\n"),
    },
  },
  light_signup: {
    es: {
      subject: "Gracias por tu registro — LA MESA",
      body: [
        "Gracias {{fullName}} por tu inscripción a LA MESA.",
        "",
        "Para poder invitarte a futuros eventos y cenas de alto nivel, necesitamos que completes tu perfil en cuanto puedas.",
        "",
        "Inicia sesión con el correo usado al registrarte ({{email}}) — Google, o crea una contraseña en la página de acceso — para abrir tu perfil:",
        "{{loginUrl}}",
        "",
        "Quedamos a tus órdenes,",
        "LA MESA",
      ].join("\n"),
    },
    fr: {
      subject: "Merci pour ton inscription — LA MESA",
      body: [
        "Merci {{fullName}} pour ton inscription à LA MESA.",
        "",
        "Pour pouvoir t’inviter à participer à de futurs événements et dîners qualifiés, nous avons besoin que tu complètes rapidement ton profil dès que tu auras le temps.",
        "",
        "Connecte-toi avec l’email utilisé à l’inscription ({{email}}) — Google, ou crée un mot de passe sur la page de connexion — pour accéder à ton profil :",
        "{{loginUrl}}",
        "",
        "À bientôt,",
        "LA MESA",
      ].join("\n"),
    },
    en: {
      subject: "Thanks for signing up — LA MESA",
      body: [
        "Thank you {{fullName}} for signing up to LA MESA.",
        "",
        "To invite you to future events and curated dinners, we need you to complete your profile as soon as you can.",
        "",
        "Sign in with the email you used to register ({{email}}) — Google, or create a password on the sign-in page — to open your profile:",
        "{{loginUrl}}",
        "",
        "See you soon,",
        "LA MESA",
      ].join("\n"),
    },
  },
  referral_invite: {
    es: {
      subject: "{{sponsorName}} te invita a unirte a LA MESA",
      body: [
        "Estimado/a:",
        "",
        "LA MESA es una red privada de cenas profesionales selectas: mesas reducidas, conversaciones de alto valor y sin networking superficial.",
        "",
        "{{sponsorName}} te ha invitado a unirte a LA MESA.",
        "",
        "Regístrate sin costo aquí. Próximamente recibirás una invitación para participar en una cena.",
        "{{inviteUrl}}",
        "",
        "LA MESA — cenas privadas exclusivas.",
      ].join("\n"),
    },
    fr: {
      subject: "{{sponsorName}} vous a invité à rejoindre LA MESA",
      body: [
        "Bonjour,",
        "",
        "LA MESA est un réseau privé de dîners professionnels sélectionnés — petites tables, conversations à forte valeur, sans networking froid.",
        "",
        "{{sponsorName}} vous a invité à rejoindre LA MESA.",
        "",
        "Inscrivez-vous gratuitement ici et recevez prochainement une invitation à participer à un dîner.",
        "{{inviteUrl}}",
        "",
        "LA MESA — dîners privés exclusifs.",
      ].join("\n"),
    },
    en: {
      subject: "{{sponsorName}} invited you to join LA MESA",
      body: [
        "Hello,",
        "",
        "LA MESA is a private network of curated professional dinners — small tables, high-signal conversations, no cold networking.",
        "",
        "{{sponsorName}} invited you to join LA MESA.",
        "",
        "Sign up for free here. You’ll soon receive an invitation to attend a dinner.",
        "{{inviteUrl}}",
        "",
        "LA MESA — exclusive private dinners.",
      ].join("\n"),
    },
  },
};

export function resolveTemplateLocale(raw?: string | null): TemplateLocale {
  if (raw === "fr" || raw === "en" || raw === "es") return raw;
  return DEFAULT_SEND_LOCALE;
}

export function defaultEmailTemplate(
  key: EmailTemplateKey,
  locale: TemplateLocale = DEFAULT_SEND_LOCALE,
): EmailTemplateDoc {
  const locales = DEFAULTS[key];
  const pair = locales[locale] ?? locales[DEFAULT_SEND_LOCALE];
  return {
    key,
    locale,
    subject: pair.subject,
    body: pair.body,
    locales,
    enabled: true,
  };
}

export function defaultLocaleContent(
  key: EmailTemplateKey,
  locale: TemplateLocale,
): LocalePair {
  return DEFAULTS[key][locale] ?? DEFAULTS[key][DEFAULT_SEND_LOCALE];
}
